# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
