# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-17 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180216_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='set_password_token',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
    ]
