# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-17 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_organizationuser_set_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuser',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='organizationusertoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='users.OrganizationUser'),
        ),
    ]
