# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-19 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180218_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='set_password_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
