# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_organizationuser_set_password_token_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationuser',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='staffuser',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='surnames',
            field=models.TextField(db_index=True, default='_', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffuser',
            name='surnames',
            field=models.TextField(db_index=True, default='_', max_length=100),
            preserve_default=False,
        ),
    ]
