# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0060_auto_20180328_2025'),
        ('users', '0010_full_name_split'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('first_name', models.TextField(db_index=True, max_length=100)),
                ('surnames', models.TextField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('set_password_token', models.TextField(blank=True, db_index=True, default='')),
                ('set_password_token_created', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Donor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonorUserToken',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='users.DonorUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
