# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_donoruser_donorusertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='donoruser',
            name='is_mainuser',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='is_mainuser',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
