# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-23 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_set_mainuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('first_name', models.TextField(db_index=True, max_length=100)),
                ('surnames', models.TextField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.TextField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
