# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-25 00:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_volunteeruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donoruser',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteeruser',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
