# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180525_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeruser',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
