# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_volunteeruser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeruser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteeruser',
            name='phone',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
