# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 01:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.TextField(choices=[('google_sheets', 'Google Sheets'), ('chucky', 'Chucky')])),
                ('action_type', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('sub_organization', models.TextField(blank=True)),
                ('budget', models.FloatField(null=True)),
                ('spent', models.FloatField(null=True)),
                ('percent_complete', models.FloatField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('contact', django.contrib.postgres.fields.jsonb.JSONField(help_text='Contact data')),
                ('key', models.TextField(help_text='Essentially google sheet row number')),
                ('source', models.TextField(choices=[('google_sheets', 'Google Sheets'), ('chucky', 'Chucky')])),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.TextField(choices=[('google_sheets', 'Google Sheets'), ('chucky', 'Chucky')])),
                ('action_type', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('sub_organization', models.TextField(blank=True)),
                ('budget', models.FloatField(null=True)),
                ('spent', models.FloatField(null=True)),
                ('percent_complete', models.FloatField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('contact', django.contrib.postgres.fields.jsonb.JSONField(help_text='Contact data')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Action')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.TextField()),
                ('cvegeo', models.TextField(unique=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(help_text='File URLs, etc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(help_text='Observation form data, such as description, type, file URLs')),
                ('source_id', models.TextField(help_text="Identifier for observation's source")),
                ('schema_id', models.TextField(help_text="Identifier for observation's schema")),
                ('recorded', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Locality')),
            ],
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('contact', django.contrib.postgres.fields.jsonb.JSONField(help_text='Contact data')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(help_text='Data for this observation, generated by DS')),
                ('version', models.TextField(help_text='Lets DS change structure without breaking clients')),
                ('data_set', models.TextField(help_text='Data set/source of this observation')),
                ('recorded', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('generator', models.ForeignKey(help_text='Organization that generated this observation', on_delete=django.db.models.deletion.CASCADE, to='map.Organization')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Locality')),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='observer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='map.Observer'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Locality'),
        ),
        migrations.AddField(
            model_name='action',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Locality'),
        ),
        migrations.AddField(
            model_name='action',
            name='organization',
            field=models.ForeignKey(help_text='Frozen after first read', on_delete=django.db.models.deletion.CASCADE, to='map.Organization'),
        ),
        migrations.AddIndex(
            model_name='organizationobservation',
            index=models.Index(fields=['location'], name='map_organiz_locatio_693305_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationobservation',
            index=models.Index(fields=['recorded'], name='map_organiz_recorde_4085ed_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['location'], name='map_observa_locatio_b30970_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['recorded'], name='map_observa_recorde_525382_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set([('key', 'organization')]),
        ),
    ]
