# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.TextField(choices=[('before', 'Por iniciar'), ('ongoing', 'En proceso'), ('done', 'Concluido')]),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='status',
            field=models.TextField(choices=[('before', 'Por iniciar'), ('ongoing', 'En proceso'), ('done', 'Concluido')]),
        ),
    ]
