# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 00:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20171102_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='percent_complete',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='percent_complete',
        ),
        migrations.AddField(
            model_name='action',
            name='action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='action',
            name='target',
            field=models.FloatField(help_text='How many units does action intend to deliver', null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='unit_of_measurement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='target',
            field=models.FloatField(help_text='How many units does action intend to deliver', null=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='unit_of_measurement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='munipality_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='state_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='budget',
            field=models.FloatField(help_text='$MXN', null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='end_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='spent',
            field=models.FloatField(help_text='$MXN', null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='start_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.TextField(blank=True, choices=[('before', 'Por iniciar'), ('ongoing', 'En proceso'), ('done', 'Concluido')]),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='budget',
            field=models.FloatField(help_text='$MXN', null=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='end_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='spent',
            field=models.FloatField(help_text='$MXN', null=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='start_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='status',
            field=models.TextField(blank=True, choices=[('before', 'Por iniciar'), ('ongoing', 'En proceso'), ('done', 'Concluido')]),
        ),
        migrations.AlterField(
            model_name='locality',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='File URLs, etc', null=True),
        ),
    ]
