# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 00:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20171103_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='key',
            field=models.TextField(default='_', help_text='Essentially google sheet tab name', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='Contact data'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
