# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20171103_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='action',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='description',
            new_name='long_desc',
        ),
        migrations.RenameField(
            model_name='actionlog',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='description',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='long_desc',
            field=models.TextField(blank=True),
        ),
    ]
