# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20171104_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.TextField(blank=True, choices=[('before', 'Por iniciar'), ('ongoing', 'En proceso'), ('cancelled', 'Cancelada'), ('done', 'Concluida')]),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='status',
            field=models.TextField(blank=True, choices=[('before', 'Por iniciar'), ('ongoing', 'En proceso'), ('cancelled', 'Cancelada'), ('done', 'Concluida')]),
        ),
    ]
