# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20171104_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='action',
            name='long_desc',
        ),
        migrations.RemoveField(
            model_name='action',
            name='spent',
        ),
        migrations.RemoveField(
            model_name='action',
            name='status',
        ),
        migrations.RemoveField(
            model_name='action',
            name='sub_organization',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='long_desc',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='spent',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='sub_organization',
        ),
        migrations.AddField(
            model_name='action',
            name='progress',
            field=models.FloatField(help_text='How many units have been delivered', null=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='progress',
            field=models.FloatField(help_text='How many units have been delivered', null=True),
        ),
    ]
