# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 22:20
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20171217_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locality',
            name='state_name',
        ),
        migrations.AddField(
            model_name='locality',
            name='elevation',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locality',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='', srid=4326),
            preserve_default=False,
        ),
    ]
