# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_auto_20171217_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='state_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
