# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_locality_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='elevation',
            field=models.FloatField(null=True),
        ),
    ]
