# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 20:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20171218_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('cvegeo', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('denue_id', models.TextField(blank=True)),
                ('nom_estab', models.TextField(blank=True)),
                ('raz_social', models.TextField(blank=True)),
                ('codigo_act', models.TextField(blank=True)),
                ('nombre_act', models.TextField(blank=True)),
                ('per_ocu', models.TextField(blank=True)),
                ('tipo_vial', models.TextField(blank=True)),
                ('nom_vial', models.TextField(blank=True)),
                ('tipo_v_e_1', models.TextField(blank=True)),
                ('nom_v_e_1', models.TextField(blank=True)),
                ('tipo_v_e_2', models.TextField(blank=True)),
                ('nom_v_e_2', models.TextField(blank=True)),
                ('tipo_v_e_3', models.TextField(blank=True)),
                ('nom_v_e_3', models.TextField(blank=True)),
                ('numero_ext', models.TextField(blank=True)),
                ('letra_ext', models.TextField(blank=True)),
                ('edificio', models.TextField(blank=True)),
                ('edificio_e', models.TextField(blank=True)),
                ('numero_int', models.TextField(blank=True)),
                ('letra_int', models.TextField(blank=True)),
                ('tipo_asent', models.TextField(blank=True)),
                ('nomb_asent', models.TextField(blank=True)),
                ('tipoCenCom', models.TextField(blank=True)),
                ('nom_CenCom', models.TextField(blank=True)),
                ('num_local', models.TextField(blank=True)),
                ('cod_postal', models.TextField(blank=True)),
                ('cve_ent', models.TextField(blank=True)),
                ('entidad', models.TextField(blank=True)),
                ('cve_mun', models.TextField(blank=True)),
                ('municipio', models.TextField(blank=True)),
                ('cve_loc', models.TextField(blank=True)),
                ('localidad', models.TextField(blank=True)),
                ('ageb', models.TextField(blank=True)),
                ('manzana', models.TextField(blank=True)),
                ('telefono', models.TextField(blank=True)),
                ('correoelec', models.TextField(blank=True)),
                ('www', models.TextField(blank=True)),
                ('tipoUniEco', models.TextField(blank=True)),
                ('latitud', models.TextField(blank=True)),
                ('longitud', models.TextField(blank=True)),
                ('fecha_alta', models.TextField(blank=True)),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.Locality')),
            ],
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['cvegeo'], name='map_establi_cvegeo_5e46a1_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['location'], name='map_establi_locatio_76d7ae_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['codigo_act'], name='map_establi_codigo__dbd338_idx'),
        ),
    ]
