# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 23:06
from __future__ import unicode_literals

import db.map.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_auto_20171218_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScianGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='establishment',
            name='codigo_act',
            field=models.TextField(blank=True, help_text='CVE_SCIAN'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='denue_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='nombre_act',
            field=models.TextField(blank=True, help_text='DESC_SCIAN'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='scian_group',
            field=models.ForeignKey(default=db.map.models.default_scian_group, on_delete=django.db.models.deletion.CASCADE, to='map.ScianGroup'),
        ),
    ]
