# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 23:06
from __future__ import unicode_literals

import db.map.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_auto_20171218_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScianGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
