# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 23:06
from __future__ import unicode_literals

import db.map.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_auto_20171218_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='codigo_act',
            field=models.TextField(blank=True, help_text='CVE_SCIAN'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='denue_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='nombre_act',
            field=models.TextField(blank=True, help_text='DESC_SCIAN'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='scian_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.ScianGroup'),
        ),
    ]
