# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_auto_20171218_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='has_data',
            field=models.BooleanField(db_index=True, default=False, help_text='Has additional data'),
        ),
    ]
