# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_organization_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='year_established',
            field=models.IntegerField(null=True),
        ),
    ]
