# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_organization_year_established'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='year_established',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
