# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 16:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_auto_20180106_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='locality',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='Metrics, file URLs, etc'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='Metrics, file URLs, etc'),
        ),
        migrations.AlterField(
            model_name='state',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='Metrics, file URLs, etc'),
        ),
    ]
