# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 16:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_auto_20180107_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='budget',
            field=models.FloatField(blank=True, help_text='$MXN', null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='progress',
            field=models.FloatField(blank=True, help_text='How many units have been delivered?', null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='target',
            field=models.FloatField(blank=True, help_text='How many units does action intend to deliver', null=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='budget',
            field=models.FloatField(blank=True, help_text='$MXN', null=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='progress',
            field=models.FloatField(blank=True, help_text='How many units have been delivered?', null=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='target',
            field=models.FloatField(blank=True, help_text='How many units does action intend to deliver', null=True),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.Locality'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationobservation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
