# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0023_auto_20180107_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='observer',
        ),
        migrations.RemoveField(
            model_name='organizationobservation',
            name='generator',
        ),
        migrations.RemoveField(
            model_name='organizationobservation',
            name='locality',
        ),
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('-end_date', '-start_date', '-modified')},
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='Observer',
        ),
        migrations.DeleteModel(
            name='OrganizationObservation',
        ),
    ]
