# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 01:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_auto_20180111_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(help_text='Submission data and metadata, such as description, type, file URLs')),
                ('source', models.TextField(choices=[('kobo', 'KoBo')])),
                ('submitted', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('image_urls', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[])),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.Action')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['location'], name='map_submiss_locatio_5cad3c_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['source'], name='map_submiss_source_18dcbc_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted'], name='map_submiss_submitt_2f2bec_idx'),
        ),
    ]
