# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0025_auto_20180111_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='kobo_id',
            field=models.UUIDField(null=True),
        ),
    ]
