# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0026_organization_kobo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='kobo_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
