# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0028_auto_20180111_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='kobo_id',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='submission',
            name='source_id',
            field=models.TextField(choices=[('kobo', 'KoBo')], default=0),
            preserve_default=False,
        ),
    ]
