# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0030_auto_20180111_0254'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='submission',
            name='map_submiss_source_54d516_idx',
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('source', 'source_id')]),
        ),
    ]
