# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0033_auto_20180111_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='published',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
