# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0035_auto_20180112_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='secret_key',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
