# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 00:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0036_auto_20180112_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
