# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0037_auto_20180116_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-submitted',)},
        ),
    ]
