# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0039_auto_20180122_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='key',
        ),
        migrations.AlterField(
            model_name='action',
            name='key',
            field=models.IntegerField(blank=True, help_text='Auto-incremented number for actions in organization'),
        ),
    ]
