# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-17 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0041_remove_action_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='desc',
            field=models.TextField(),
        ),
    ]
