# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-18 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0042_auto_20180217_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='desc',
            field=models.TextField(blank=True, help_text='Can complement description inside of `data`'),
        ),
    ]
