# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0043_submission_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='published',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
