# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-19 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0044_submission_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='addr',
            field=models.TextField(blank=True, help_text='Can complement address inside of `data`'),
        ),
    ]
