# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-03 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0046_auto_20180303_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='image_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
