# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-03 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0047_action_image_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='donors',
        ),
    ]
