# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-03 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0048_remove_action_donors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='start_date',
            new_name='received_date',
        ),
    ]
