# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0050_auto_20180307_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
