# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0051_auto_20180307_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='deleted',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='actionlog',
            old_name='deleted',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='deleted',
            new_name='archived',
        ),
    ]
