# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0054_data_image_urls_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='year_established',
            field=models.IntegerField(null=True),
        ),
    ]
