# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0056_auto_20180323_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='year_established',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
