# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0057_auto_20180325_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='accepting_help',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
