# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0058_organization_accepting_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='help_desc',
            field=models.TextField(blank=True),
        ),
    ]
