# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0059_organization_help_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='donation',
            name='approved_by_donor',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='approved_by_org',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='organization',
            field=models.OneToOneField(blank=True, help_text='Is donor also an organization?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor', to='map.Organization'),
        ),
    ]
