# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 22:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0060_auto_20180328_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='website',
        ),
        migrations.AddField(
            model_name='donor',
            name='contact',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='Contact data'),
        ),
        migrations.AddField(
            model_name='donor',
            name='sector',
            field=models.TextField(blank=True, choices=[('civil', 'Civil'), ('public', 'Público'), ('private', 'Privado'), ('religious', 'Religioso')], db_index=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='year_established',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
