# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-06 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0061_auto_20180405_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donating',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='donating_desc',
            field=models.TextField(blank=True),
        ),
    ]
