# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0062_auto_20180406_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('app_type', models.TextField(choices=[('web', 'web'), ('backend', 'backend')], db_index=True)),
                ('git_hash', models.TextField(db_index=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
