# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0063_appversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_type', models.TextField()),
                ('frequency_hours', models.IntegerField()),
                ('target', models.IntegerField(blank=True, db_index=True, null=True)),
                ('sent', models.IntegerField(blank=True, db_index=True, default=0)),
                ('last_sent', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('done', models.DateTimeField(blank=True, db_index=True, default=False)),
            ],
            options={
                'ordering': ('done', '-last_sent'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='emailnotification',
            unique_together=set([('email', 'email_type')]),
        ),
    ]
