# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-25 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0064_auto_20180425_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailnotification',
            old_name='frequency_hours',
            new_name='period_hours',
        ),
    ]
