# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0064_auto_20180425_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='wait_hours',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
