# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0065_emailnotification_wait_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='pretty',
            field=models.BooleanField(default=True),
        ),
    ]
