# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-01 13:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0066_emailnotification_pretty'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoursePostEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('discourse_user_id', models.IntegerField(db_index=True)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscourseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('discourse_user_id', models.IntegerField(unique=True)),
                ('discourse_external_id', models.IntegerField(db_index=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
