# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-01 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0067_discoursepostevent_discourseuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discourseuser',
            name='discourse_external_id',
            field=models.TextField(db_index=True),
        ),
    ]
