# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-01 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0070_auto_20180501_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discourseuser',
            name='discourse_external_id',
        ),
        migrations.AlterField(
            model_name='discourseuser',
            name='email',
            field=models.EmailField(help_text='Same as Discourse `external_id`', max_length=254, unique=True),
        ),
    ]
