# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-01 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0071_auto_20180501_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoursetopicevent',
            name='discourse_user_id',
            field=models.IntegerField(db_index=True, default=11),
            preserve_default=False,
        ),
    ]
