# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-16 21:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0073_auto_20180503_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='image_urls',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='submission',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='Submission data and metadata'),
        ),
    ]
