# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-23 15:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_volunteeruser'),
        ('map', '0074_auto_20180516_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('reason_why', models.TextField()),
                ('days_volunteered', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerOpportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name_of_position', models.TextField()),
                ('required_skills', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('desc', models.TextField()),
                ('location_desc', models.TextField()),
                ('transport_included', models.BooleanField(default=False)),
                ('food_included', models.BooleanField(default=False)),
                ('target', models.FloatField(help_text='How many volunteers does this project need?')),
                ('progress', models.FloatField(help_text='How many volunteers have signed up?')),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.RemoveField(
            model_name='organization',
            name='accepting_help',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='help_desc',
        ),
        migrations.AlterField(
            model_name='action',
            name='target',
            field=models.FloatField(blank=True, help_text='How many units does action intend to deliver?', null=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='target',
            field=models.FloatField(blank=True, help_text='How many units does action intend to deliver?', null=True),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Action'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.VolunteerOpportunity'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.VolunteerUser'),
        ),
    ]
