# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-23 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0075_auto_20180523_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='published',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
