# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-23 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0076_volunteeropportunity_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='from_anywhere',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='location_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='progress',
            field=models.FloatField(blank=True, default=0, help_text='How many volunteers have signed up?'),
        ),
    ]
