# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-26 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0077_auto_20180523_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteeropportunity',
            old_name='name_of_position',
            new_name='position',
        ),
    ]
