# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-26 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0078_auto_20180526_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='progress',
            field=models.IntegerField(blank=True, default=0, help_text='How many volunteers have signed up?'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='target',
            field=models.IntegerField(help_text='How many volunteers does this project need?'),
        ),
    ]
