# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0079_auto_20180526_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
