# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-30 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0080_volunteeropportunity_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteeropportunity',
            name='from_anywhere',
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='location',
            field=models.TextField(choices=[('anywhere', 'anywhere'), ('in_locality', 'in_locality'), ('other', 'other')], db_index=True, default='anywhere'),
            preserve_default=False,
        ),
    ]
