# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-30 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0081_auto_20180530_0512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteerapplication',
            options={'ordering': ('-created',)},
        ),
    ]
