# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-01 23:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_volunteeruser_age'),
        ('map', '0082_auto_20180530_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Action')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.VolunteerUser')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
