# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20180604_1544'),
        ('map', '0083_share'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='share',
            unique_together=set([('action', 'user')]),
        ),
    ]
