# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 17:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0084_auto_20180604_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326)),
                ('desc', models.TextField()),
                ('addr', models.TextField(blank=True)),
                ('video', django.contrib.postgres.fields.jsonb.JSONField()),
                ('recipient', django.contrib.postgres.fields.jsonb.JSONField()),
                ('submitted', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Action')),
            ],
            options={
                'ordering': ('-submitted',),
            },
        ),
    ]
