# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0085_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('access_token', models.TextField()),
                ('expires_in', models.IntegerField()),
                ('token_type', models.TextField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
