# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-18 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0086_youtubeaccesstoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='recipient',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='recipients',
            field=models.TextField(default='kyle,eddie, daniel galan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
