# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-23 21:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0087_auto_20180618_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='preview',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
