# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-27 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0089_action_status_by_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='level',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='action',
            name='score',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
