# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-27 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0090_auto_20180627_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='level',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
