# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-29 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0091_auto_20180627_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='score',
            field=models.FloatField(blank=True, db_index=True, default=0),
        ),
    ]
