# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-06 00:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0092_auto_20180629_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='preview',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
