# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-18 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0093_action_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='beneficiaries_criteria',
            field=models.TextField(blank=True, help_text='How are beneficiaries selected?'),
        ),
        migrations.AddField(
            model_name='action',
            name='beneficiaries_desc',
            field=models.TextField(blank=True, help_text='What kind of people get to be beneficiaries?'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='beneficiaries_criteria',
            field=models.TextField(blank=True, help_text='How are beneficiaries selected?'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='beneficiaries_desc',
            field=models.TextField(blank=True, help_text='What kind of people get to be beneficiaries?'),
        ),
    ]
