# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-18 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0094_auto_20180718_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='beneficiaries_criteria_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='beneficiaries_criteria_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='beneficiaries_criteria',
            field=models.TextField(blank=True, choices=[('convocatoria_abierta', 'convocatoria abierta'), ('convocatoria_cerrada', 'convocatoria cerrada (invitación directa a presentar proyectos)'), ('mapeo_directo_de_necesidades', 'mapeo directo de necesidades'), ('other', 'other'), ('', '')], help_text='How are beneficiaries selected?'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='beneficiaries_criteria',
            field=models.TextField(blank=True, choices=[('convocatoria_abierta', 'convocatoria abierta'), ('convocatoria_cerrada', 'convocatoria cerrada (invitación directa a presentar proyectos)'), ('mapeo_directo_de_necesidades', 'mapeo directo de necesidades'), ('other', 'other'), ('', '')], help_text='How are beneficiaries selected?'),
        ),
    ]
