# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-23 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0096_auto_20180718_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='progress',
            field=models.FloatField(blank=True, default=0, help_text='How many units have been delivered?'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='progress',
            field=models.FloatField(blank=True, default=0, help_text='How many units have been delivered?'),
        ),
    ]
