FROM python:3.6
ENV PYTHONUNBUFFERED 1

ADD requirements.txt /requirements.txt

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
        gdal-bin \
        lsof \
    && rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt

RUN mkdir /code/
WORKDIR /code/
ADD ./src /code/

CMD ["celery", "worker", "-A", "config"]
