FROM python:3.6
ENV PYTHONUNBUFFERED 1

ADD requirements.txt /requirements.txt

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
        gdal-bin \
        lsof \
    && rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt

RUN mkdir /code/
WORKDIR /code/
ADD ./src /code/

EXPOSE 8000
ENTRYPOINT ["/code/docker-entrypoint.sh"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
