FROM python:3.5

ADD requirements-dev.txt /requirements-dev.txt

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
        gdal-bin \
        lsof \
    && rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements-dev.txt

RUN mkdir /code/
WORKDIR /code/
ADD . /code/

CMD ["celery", "beat", "-A", "config"]
